//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyDescription("chocolatey is a product of Chocolatey Software, Inc. - All Rights Reserved.")]
[assembly: AssemblyCompany("Chocolatey Software, Inc.")]
[assembly: AssemblyProduct("Chocolatey")]
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: AssemblyInformationalVersion("2.0.0-alpha-20260331-27870be5")]
[assembly: AssemblyCopyright("Copyright © 2017 - 2026 Chocolatey Software, Inc. Copyright © 2011 - 2017, RealDimensions Software, LLC - All Rights Reserved.")]
[assembly: AssemblyTrademark("Chocolatey - Chocolatey Software, Inc.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]

// Custom Attributes
[assembly: ObfuscateAssembly(false)]
